version: '2.4'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: pass
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: pass
      MYSQL_PASSWORD: pass
    restart: always
    ports:
      - "8080:80"
    networks:
      - backend_network

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"

  auth:
    build:
      context: ./auth
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./auth:/app/
    environment:
      - SERVICE=auth
    env_file:
      - ./auth/.env
    depends_on:
      - mysql
      - rabbitmq
      
networks:
  backend_network:
    driver: bridge

volumes:
  data:


