version: "2.4"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: pass
      MYSQL_PASSWORD: pass
    restart: always
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    networks:
      - backend_network

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    restart: always

  auth:
    build:
      context: ./auth
      args:
        - NODE_ENV=development
      target: dev
      dockerfile: Dockerfile
    ports:
      - ${AUTH_SERVICE_PORT}:3001
    volumes:
      - ./auth:/app/
    environment:
      - SERVICE=auth
    restart: always
    env_file:
      - ./auth/.env
    networks:
      - backend_network
    depends_on:
      - mysql
      - rabbitmq

  admin_app:
    build:
      target: dev
      context: ./frontend/admin
      dockerfile: Dockerfile
    ports:
      - ${ADMIN_APP_PORT}:3000
    restart: always
    volumes:
      - ./frontend/admin:/app/

  user_app:
    build:
      target: dev
      context: ./frontend/user
      dockerfile: Dockerfile
    ports:
      - ${USER_APP_PORT}:3000
    restart: always
    volumes:
      - ./frontend/user:/app/

networks:
  backend_network:
    driver: bridge

volumes:
  data:
