version: '2.4'

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: naturopura_main
      MYSQL_USER: db_user
      MYSQL_PASSWORD: user
    ports:
      - "6033:3306"
    volumes:
      - data:/var/lib/mysql
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"

  auth:
    build:
      context: ./auth
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./auth:/app/
    environment:
      - SERVICE=auth
    env_file:
      - ./auth/.env
    depends_on:
      - mysql
      - rabbitmq

  products:
    build:
      context: ./products
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3002:3002"
    volumes:
      - ./products:/app/
    environment:
      - SERVICE=products
    env_file:
      - ./products/.env
    depends_on:
      - mysql
      - rabbitmq

  orders:
    build:
      context: ./orders
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3003:3003"
    volumes:
      - ./orders:/app/
    environment:
      - SERVICE=orders
    env_file:
      - ./orders/.env
    depends_on:
      - mysql
      - rabbitmq

volumes:
  data:


