const uiTexts = {
  en: {
    uploadImage: "Upload Image",
    uploadDescription: "Take a clear photo of the affected plant part (leaf, stem, or fruit)",
    clickToUpload: "Click to upload or drag and drop",
    changeImage: "Change Image",
    detectButton: "Detect Crop Health",
    analyzing: "Analyzing...",
    detectionResults: "Detection Results",
    plantInformation: "Plant Information",
    name: "Name",
    diseaseInformation: "Disease Information",
    pestInformation: "Pest Information",
    issue: "Issue",
    pest: "Pest",
    symptoms: "Symptoms",
    damage: "Damage",
    treatment: "Treatment",
    control: "Control",
    causes: "Causes",
    biology: "Biology/Causes",
    noDiseaseDetected: "No disease detected",
    noPestDetected: "No pest detected",
    aiIdentified: "AI Identified",
    fromDatabase: "From Database",
    noSpecificSymptoms: "No specific symptoms provided.",
    noSpecificDamage: "No specific damage provided.",
    noSpecificTreatment: "No specific treatment recommendations.",
    noSpecificControl: "No specific control methods.",
    noSpecificCauses: "No specific causes information available.",
    noSpecificBiologyCauses: "No specific biology/causes information available.",
    downloadPDF: "Download PDF",
    uploadedImageForPDF: "Uploaded Image:",
    reportTitle: "Crop Health Report",
    date: "Date:",
    location: "Location:",
    fetchBlockchainResults: "Fetch Blockchain Results",
    storeOnBlockchain: "Store on Blockchain",
    blockchainResults: "Blockchain Results",
    noBlockchainResults: "No blockchain results found",
    previousDetections: "Previous Detections",
    detectionDate: "Detection Date",
  },
  hi: {
    uploadImage: "छवि अपलोड करें",
    uploadDescription: "प्रभावित पौधे के हिस्से (पत्ती, तना या फल) की स्पष्ट फोटो लें",
    clickToUpload: "अपलोड करने के लिए क्लिक करें या खींचें और छोड़ें",
    changeImage: "छवि बदलें",
    detectButton: "फसल का स्वास्थ्य पता लगाएं",
    analyzing: "विश्लेषण हो रहा है...",
    detectionResults: "पता लगाने के परिणाम",
    plantInformation: "पौधे की जानकारी",
    name: "नाम",
    diseaseInformation: "रोग की जानकारी",
    pestInformation: "कीट की जानकारी",
    issue: "समस्या",
    pest: "कीट",
    symptoms: "लक्षण",
    damage: "क्षति",
    treatment: "उपचार",
    control: "नियंत्रण",
    causes: "कारण",
    biology: "जीव विज्ञान/कारण",
    noDiseaseDetected: "कोई रोग नहीं पाया गया",
    noPestDetected: "कोई कीट नहीं पाया गया",
    aiIdentified: "एआई द्वारा पहचाना गया",
    fromDatabase: "डेटाबेस से",
    noSpecificSymptoms: "कोई विशिष्ट लक्षण प्रदान नहीं किए गए।",
    noSpecificDamage: "कोई विशिष्ट क्षति प्रदान नहीं की गई।",
    noSpecificTreatment: "कोई विशिष्ट उपचार सुझाव नहीं।",
    noSpecificControl: "कोई विशिष्ट नियंत्रण विधि नहीं।",
    noSpecificCauses: "कोई विशिष्ट कारण जानकारी उपलब्ध नहीं।",
    noSpecificBiologyCauses: "कोई विशिष्ट जीव विज्ञान/कारण जानकारी उपलब्ध नहीं।",
    downloadPDF: "पीडीएफ डाउनलोड करें",
    uploadedImageForPDF: "अपलोड की गई छवि:",
    reportTitle: "फसल स्वास्थ्य रिपोर्ट",
    date: "दिनांक:",
    location: "स्थान:",
    fetchBlockchainResults: "ब्लॉकचेन परिणाम प्राप्त करें",
    storeOnBlockchain: "ब्लॉकचेन पर स्टोर करें",
    blockchainResults: "ब्लॉकचेन परिणाम",
    noBlockchainResults: "कोई ब्लॉकचेन परिणाम नहीं मिला",
    previousDetections: "पिछली जांचें",
    detectionDate: "जांच की तारीख",
  },
  or: { // Odia Translations
    uploadImage: "ଛବି ଅପଲୋଡ୍ କରନ୍ତୁ",
    uploadDescription: "ପ୍ରଭାବିତ ଗଛର ଅଂଶ (ପତ୍ର, କାଣ୍ଡ, କିମ୍ବା ଫଳ) ର ଏକ ସ୍ପଷ୍ଟ ଫଟୋ ଉଠାନ୍ତୁ",
    clickToUpload: "ଅପଲୋଡ୍ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ କିମ୍ବା ଟାଣି ଆଣି ଛାଡନ୍ତୁ",
    changeImage: "ଛବି ବଦଳାନ୍ତୁ",
    detectButton: "ଫସଲ ସ୍ୱାସ୍ଥ୍ୟ ଚିହ୍ନଟ କରନ୍ତୁ",
    analyzing: "ବିଶ୍ଳେଷଣ କରାଯାଉଛି...",
    detectionResults: "ଚିହ୍ନଟ ଫଳାଫଳ",
    plantInformation: "ଗଛର ସୂଚନା",
    name: "ନାମ",
    diseaseInformation: "ରୋଗ ସୂଚନା",
    pestInformation: "କୀଟ ସୂଚନା",
    issue: "ସମସ୍ୟା",
    pest: "କୀଟ",
    symptoms: "ଲକ୍ଷଣ",
    damage: "କ୍ଷତି",
    treatment: "ଚିକିତ୍ସା",
    control: "ନିୟନ୍ତ୍ରଣ",
    causes: "କାରଣ",
    biology: "ଜୀବ ବିଜ୍ଞାନ/କାରଣ",
    noDiseaseDetected: "କୌଣସି ରୋଗ ଚିହ୍ନଟ ହୋଇନାହିଁ",
    noPestDetected: "କୌଣସି କୀଟ ଚିହ୍ନଟ ହୋଇନାହିଁ",
    aiIdentified: "AI ଦ୍ୱାରା ଚିହ୍ନଟ",
    fromDatabase: "ଡାଟାବେସ୍ ରୁ",
    noSpecificSymptoms: "କୌଣସି ନିର୍ଦ୍ଦିଷ୍ଟ ଲକ୍ଷଣ ପ୍ରଦାନ କରାଯାଇ ନାହିଁ ।",
    noSpecificDamage: "କୌଣସି ନିର୍ଦ୍ଦିଷ୍ଟ କ୍ଷତି ପ୍ରଦାନ କରାଯାଇ ନାହିଁ ।",
    noSpecificTreatment: "କୌଣସି ନିର୍ଦ୍ଦିଷ୍ଟ ଚିକିତ୍ସା ସୁପାରିଶ ନାହିଁ ।",
    noSpecificControl: "କୌଣସି ନିର୍ଦ୍ଦିଷ୍ଟ ନିୟନ୍ତ୍ରଣ ପଦ୍ଧତି ନାହିଁ ।",
    noSpecificCauses: "କୌଣସି ନିର୍ଦ୍ଦିଷ୍ଟ କାରଣ ସୂଚନା ଉପଲବ୍ଧ ନାହିଁ ।",
    noSpecificBiologyCauses: "କୌଣସି ନିର୍ଦ୍ଦିଷ୍ଟ ଜୀବ ବିଜ୍ଞାନ/କାରଣ ସୂଚନା ଉପଲବ୍ଧ ନାହିଁ ।",
    downloadPDF: "PDF ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
    uploadedImageForPDF: "ଅପଲୋଡ୍ ହୋଇଥିବା ଛବି:",
    reportTitle: "ଫସଲ ସ୍ୱାସ୍ଥ୍ୟ ରିପୋର୍ଟ",
    date: "ତାରିଖ:",
    location: "ସ୍ଥାନ:",
    fetchBlockchainResults: "ବ୍ଲକ୍ ଚେନ୍ ଫଳାଫଳ ଆଣନ୍ତୁ",
    storeOnBlockchain: "ବ୍ଲକ୍ ଚେନ୍ ରେ ସ୍ଟୋର୍ କରନ୍ତୁ",
    blockchainResults: "ବ୍ଲକ୍ ଚେନ୍ ଫଳାଫଳ",
    noBlockchainResults: "କୌଣସି ବ୍ଲକ୍ ଚେନ୍ ଫଳାଫଳ ମିଳିଲା ନାହିଁ",
    previousDetections: "ପୂର୍ବ ନିରୀକ୍ଷଣ",
    detectionDate: "ନିରୀକ୍ଷଣ ତାରିଖ",
  }
};

export default uiTexts;
