http:
  port: 8080
  host: localhost
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth:
    host: localhost
    paths: ['/auth/user/login','/auth/user/signup']
serviceEndpoints:
  auth:
   url: 'http://auth:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - auth
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: auth 
              changeOrigin: true
