/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: [
      "images.immediate.co.uk",
      "i0.wp.com",
      "www.licious.in",
      "new.milk.org",
      "www.marionskitchen.com",
      "www.madewithlau.com",
      "www.bigbasket.com",
      "m.media-amazon.com",
      "www.savoringitaly.com",
      "www.mystore.in",
      "fattaak.in",
      "www.jiomart.com",
      "images-cdn.ubuy.co.in",
      "www.euroschoolindia.com",
      "img.freepik.com",
      "zanducare.com",
      "cdn.shopify.com",
      "5.imimg.com",
      "cdn.shopaccino.com",
      "4.imimg.com",
      "www.chandigarhayurvedcentre.com",
      "images.everydayhealth.com",
      "fruitboxco.com",
      "www.earthytales.in",
      "www.fervalle.com",
      "cdn.shopaccino.com",
      "cdn.britannica.com",
      "media.istockphoto.com",
      "happyharvestfarms.com",
      "www.mashed.com",
      "healthybuddha.in",
      "blog.cabi.org",
      "simplyfresh.info",
      "5.imimg.com",
      "www.healthxchange.sg",
      "upload.wikimedia.org",
      "www.ecepl.com",
      "kellogggarden.com",
      "cdn.mos.cms.futurecdn.net",
      "www.skorganicfarms.com,",
      "www.skorganicfarms.com",
      "www.alkarty.com",
      "www.bluetribefoods.com",
      "tailwindui.com",
    ], // Add the domain here
  },
};

export default nextConfig;
